# Generated by Django 4.1.13 on 2024-07-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
